project:
  type: website
  output-dir: docs

website:
  title: "Emily Su"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - contact.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



